"""initial migration

Revision ID: 7b5f38b06d2c
Revises: 
Create Date: 2022-01-06 20:45:08.023295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b5f38b06d2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mms_admin',
    sa.Column('create_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mms_category',
    sa.Column('create_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mms_customer',
    sa.Column('create_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.SmallInteger(), nullable=False),
    sa.Column('birthday', sa.String(length=30), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mms_product',
    sa.Column('create_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sn', sa.String(length=10), nullable=False),
    sa.Column('manufacturer', sa.String(length=30), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('standard', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['mms_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mms_product_category_id'), 'mms_product', ['category_id'], unique=False)
    op.create_index(op.f('ix_mms_product_name'), 'mms_product', ['name'], unique=False)
    op.create_table('mms_sku',
    sa.Column('create_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sku', sa.String(length=10), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('supply_count', sa.Integer(), nullable=False),
    sa.Column('sell_price', sa.Integer(), nullable=False),
    sa.Column('left_inventory', sa.Integer(), nullable=False),
    sa.Column('setting_inventory', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['mms_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mms_sku_product_id'), 'mms_sku', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mms_sku_product_id'), table_name='mms_sku')
    op.drop_table('mms_sku')
    op.drop_index(op.f('ix_mms_product_name'), table_name='mms_product')
    op.drop_index(op.f('ix_mms_product_category_id'), table_name='mms_product')
    op.drop_table('mms_product')
    op.drop_table('mms_customer')
    op.drop_table('mms_category')
    op.drop_table('mms_admin')
    # ### end Alembic commands ###
