"""add_refresh_token3

Revision ID: 7a5c1656b485
Revises: 98f00f215a7b
Create Date: 2021-10-13 11:19:27.009346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a5c1656b485'
down_revision = '98f00f215a7b'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('refresh_token')
    op.drop_table('access_token')
    op.create_table(
        'refresh_token',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('create_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                  autoincrement=False, nullable=True),
        sa.Column('update_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('header', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.Column('payload', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
        sa.Column('signature', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='refresh_token_pkey'),
        sa.UniqueConstraint('header', name='refresh_token_header_key'),
        sa.UniqueConstraint('payload', name='refresh_token_payload_key'),
        sa.UniqueConstraint('signature', name='refresh_token_signature_key')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
