"""add_refresh_token2

Revision ID: 98f00f215a7b
Revises: b4fff75ec655
Create Date: 2021-10-13 11:14:43.074732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f00f215a7b'
down_revision = 'b4fff75ec655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
