"""add_refresh_token4

Revision ID: b733e0e5803e
Revises: 7a5c1656b485
Create Date: 2021-10-13 11:32:30.840829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b733e0e5803e'
down_revision = '7a5c1656b485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refreshToken')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refreshToken',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"refreshToken_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('create_dt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('update_dt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('header', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('payload', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='refreshToken_pkey'),
    sa.UniqueConstraint('header', name='refreshToken_header_key'),
    sa.UniqueConstraint('payload', name='refreshToken_payload_key'),
    sa.UniqueConstraint('signature', name='refreshToken_signature_key')
    )
    # ### end Alembic commands ###
