"""add_refresh_token5

Revision ID: f8739b9aab28
Revises: b733e0e5803e
Create Date: 2021-10-13 11:50:49.445845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8739b9aab28'
down_revision = 'b733e0e5803e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.drop_column('refresh_token', 'user_id')
    # ### end Alembic commands ###
